# Generated by Django 4.0.6 on 2022-07-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_mes_meses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentos_ley',
            old_name='anho_id',
            new_name='Año',
        ),
        migrations.RenameField(
            model_name='documentos_ley',
            old_name='categoria_ir',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='documentos_ley',
            old_name='archivo',
            new_name='Documento',
        ),
        migrations.RenameField(
            model_name='documentos_ley',
            old_name='mes_id',
            new_name='Mes',
        ),
    ]
