# Generated by Django 4.0.6 on 2022-07-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_rename_anho_id_documentos_ley_año_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentos_ley',
            name='Año',
        ),
        migrations.RemoveField(
            model_name='documentos_ley',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='documentos_ley',
            name='Documento',
        ),
        migrations.RemoveField(
            model_name='documentos_ley',
            name='Mes',
        ),
        migrations.AddField(
            model_name='documentos_ley',
            name='anho_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.anho', verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='documentos_ley',
            name='archivo',
            field=models.FileField(null=True, upload_to='documentos/transparencia/', verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='documentos_ley',
            name='categoria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.categoria', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='documentos_ley',
            name='mes_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.meses', verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='anho',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='meses',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='Mes'),
        ),
    ]
