# Generated by Django 4.0.6 on 2022-07-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_documentos_ley_año_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anho',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meses',
            name='nombre',
            field=models.CharField(max_length=10),
        ),
    ]
