# Generated by Django 4.0.6 on 2022-07-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_categoria_id_documentos_ley_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actasmecip',
            old_name='anho_id',
            new_name='anho',
        ),
        migrations.RenameField(
            model_name='resolucionesmecip',
            old_name='anho_id',
            new_name='anho',
        ),
    ]
