# Generated by Django 4.0.6 on 2022-07-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_rename_anho_id_actasmecip_anho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circularmecip',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
