# Generated by Django 4.0.6 on 2022-07-25 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_circularmecip_circular'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementosMECIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipiosMECIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('elementos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.elementosmecip', verbose_name='Elementos')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentesMECIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('princiopios_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.principiosmecip', verbose_name='Principios')),
            ],
        ),
    ]
