# Generated by Django 4.0.6 on 2022-07-26 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_elementosmecip_principiosmecip_componentesmecip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentesmecip',
            name='princiopios_id',
        ),
        migrations.RemoveField(
            model_name='principiosmecip',
            name='elementos_id',
        ),
    ]
