# Generated by Django 4.0.6 on 2022-07-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_principiosmecip_componentes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='principiosmecip',
            old_name='componentes',
            new_name='componentes_id',
        ),
    ]
