# Generated by Django 4.0.6 on 2022-07-28 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_documentos_ley_anuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosMECIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(null=True, upload_to='documentos/MECIP/modelos/', verbose_name='Archivo')),
                ('status', models.BooleanField()),
                ('anho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.anho', verbose_name='Año')),
                ('compomentes_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.componentesmecip', verbose_name='Componentes')),
                ('elementos_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.elementosmecip', verbose_name='Elementos')),
                ('principios_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.principiosmecip', verbose_name='Principios')),
            ],
        ),
    ]
