# Generated by Django 4.0.6 on 2022-08-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_categoriablog_postblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='imagen',
            field=models.FileField(null=True, upload_to='documentos/noticias/', verbose_name='Imagen'),
        ),
    ]
