# Generated by Django 4.0.6 on 2022-08-07 17:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_postblog_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postblog',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
