# Generated by Django 4.0.6 on 2022-08-07 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_postblog_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblog',
            name='publicado_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
