# Generated by Django 4.0.6 on 2022-08-09 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_postblog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarcoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(null=True, upload_to='documentos/MarcoLegal/', verbose_name='Archivo')),
                ('status', models.BooleanField()),
                ('tipo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.tiposdocumentos', verbose_name='Tipo de Dcoumento')),
            ],
        ),
    ]
