# Generated by Django 4.0.6 on 2022-08-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0025_cargodirectivo_directivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directivos',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
