# Generated by Django 4.0.6 on 2022-08-09 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0027_consejodirectivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementosmecip',
            name='principios_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.principiosmecip', verbose_name='Principios'),
        ),
        migrations.AlterField(
            model_name='principiosmecip',
            name='componentes_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App.componentesmecip', verbose_name='Componentes'),
        ),
    ]
