# Generated by Django 4.0.6 on 2022-08-10 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0028_alter_elementosmecip_principios_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosmecip',
            name='principios_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App.principiosmecip', verbose_name='Principios'),
        ),
    ]
